"""
build_indexes.py
Phone Studio — Context Directory Indexer

Called by .github/workflows/ingest-outputs.yml
Creates/updates INDEX.md in each context/ subdirectory.
Uses wiki-link format for Obsidian compatibility.
"""

import os
import glob
import frontmatter
from datetime import datetime, timezone

# Directories to index
DIRS = [
    'context/screenshots',
    'context/conversations',
    'context/approvals',
    'context/scratch',
]


def extract_meta(filepath):
    """Read YAML frontmatter from a markdown file. Returns empty dict on failure."""
    try:
        post = frontmatter.load(filepath)
        return {
            'title':  post.get('title', ''),
            'type':   post.get('type', ''),
            'status': post.get('status', ''),
            'tags':   post.get('tags', []),
            'llm':    post.get('llm', ''),
        }
    except Exception:
        return {'title': '', 'type': '', 'status': '', 'tags': [], 'llm': ''}


def slug_to_title(basename):
    """Turn 2026-04-11-cool-caption.md into Cool Caption."""
    name = basename.replace('.md', '')
    if len(name) > 11 and name[10] == '-':
        name = name[11:]
    return name.replace('-', ' ').title()


def build_wiki_link(basename):
    """[[filename-without-extension]] for Obsidian backlinks."""
    return '[[' + basename.replace('.md', '') + ']]'


def build_index(directory, all_files, now_utc):
    """Build the full INDEX.md content for a directory."""
    dir_label = directory.split('/')[-1].title()
    rows = []

    for filepath in all_files:
        basename = os.path.basename(filepath)
        date = basename[:10] if len(basename) > 10 else 'unknown'
        meta = extract_meta(filepath)

        title  = meta['title'] or slug_to_title(basename)
        ctype  = meta['type'] or '—'
        status = meta['status'] or 'inbox'
        tags_raw = meta['tags']
        tags   = ' '.join(f'#{t}' for t in tags_raw) if tags_raw else '—'
        wiki   = build_wiki_link(basename)

        rows.append(f'| {date} | {wiki} | {title} | {ctype} | {status} | {tags} |')

    row_block = '\n'.join(rows) if rows else '| — | — | No files yet | — | — | — |'

    # Build frontmatter as a string (avoids bare --- at column 1 in YAML workflow file)
    fm_sep = '---'
    frontmatter_block = (
        f'{fm_sep}\n'
        f'generated: "{now_utc}"\n'
        f'directory: "{directory}"\n'
        f'file_count: {len(all_files)}\n'
        f'type: index\n'
        f'{fm_sep}'
    )

    hr = '---'

    content = f"""{frontmatter_block}

# {dir_label} Index

> Auto-generated by Phone Studio · Last updated: **{now_utc}**
> {len(all_files)} file(s) · Sorted newest first

| Date | File | Title | Type | Status | Tags |
|------|------|-------|------|--------|------|
{row_block}

{hr}

## How to use this index

- **Backlink**: Type `[[` in any Obsidian note to link to files listed above
- **Search**: Use Obsidian quick-switcher to find by title
- **Filter by tag**: Click any `#tag` in Obsidian to see tagged notes
- **Sync**: Updates automatically within seconds of a new push from Phone Studio

## Directory purpose

| Directory | Purpose |
|-----------|---------|
| `context/screenshots` | Raw OCR outputs and LLM-generated captions from screenshots |
| `context/conversations` | Saved Perplexity Computer conversations |
| `context/approvals` | Approved, final content — source of truth |
| `context/scratch` | In-progress drafts, not yet approved |
"""
    return content


def main():
    now_utc = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')

    for directory in DIRS:
        os.makedirs(directory, exist_ok=True)

        pattern = os.path.join(directory, '*.md')
        all_files = sorted(
            [f for f in glob.glob(pattern) if not f.endswith('INDEX.md')],
            reverse=True
        )

        index_content = build_index(directory, all_files, now_utc)
        index_path = os.path.join(directory, 'INDEX.md')

        with open(index_path, 'w') as f:
            f.write(index_content)

        print(f'Indexed {len(all_files)} file(s) -> {index_path}')

    print(f'\nAll indexes updated at {now_utc}')


if __name__ == '__main__':
    main()
